# Generated by Django 4.0.8 on 2023-01-01 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=90, verbose_name='Title')),
                ('phone_number', models.CharField(blank=True, max_length=90, verbose_name='Title')),
                ('account_type', models.CharField(choices=[('1', 'Basic'), ('2', 'Gold'), ('3', 'Platinum')], default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employerprofile', to=settings.AUTH_USER_MODEL, verbose_name='User Info')),
            ],
        ),
    ]
