version: '3'

volumes:
  jobzill_local_postgres_data: {}
  jobzill_local_postgres_data_backups: {}
  node_modules :

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: jobzill_local_django
    container_name: jobzill_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  client:
    build:
      context: .
      dockerfile: ./compose/local/client/Dockerfile
    image: jobzill_local_client
    container_name: jobzill_local_client
    depends_on:
      - django
    volumes:
      - ./client:/client
      - ./client/node_modules:/client/node_modules
      - ./client/.pnpm-store:/client/.pnpm-store
      - ./client/.next:/client/.next
    env_file:
      - ./.envs/.local/.client
    ports:
      - "80:3000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: jobzill_production_postgres
    container_name: jobzill_local_postgres
    volumes:
      - jobzill_local_postgres_data:/var/lib/postgresql/data:Z
      - jobzill_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: jobzill_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: jobzill_local_redis

  celeryworker:
    <<: *django
    image: jobzill_local_celeryworker
    container_name: jobzill_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: jobzill_local_celerybeat
    container_name: jobzill_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: jobzill_local_flower
    container_name: jobzill_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
