# Generated by Django 4.0.8 on 2023-01-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='organization/%Y/%D/%M/user/', verbose_name='logo')),
                ('location', models.CharField(max_length=250, null=True, verbose_name='location')),
                ('size', models.CharField(max_length=250)),
                ('category', models.CharField(default=None, max_length=250, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('job_posts', models.TextField(max_length=250, null=True, verbose_name='job posts')),
            ],
        ),
    ]
